import axios from "axios";
import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";

const Home = (props) => {
  const {userName, publicRepos, dataRepos} = props;

  return (
    <div>
      <Head>
        <title>Carlos Carvajal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my dev-profile
          <div className="is-size-4 mt-4">Checkout my <a href="https://www.linkedin.com/in/cxcarvaj/" target="_blank">LinkedIn</a></div>
        </h1>
      </main>
      <div className="container">
        <div className="mb-6">
          {`My name is ${userName} and I have ${publicRepos} public repositories`}
          <aside className="menu">
            <ul className="menu-list">
              <p className="menu-label mt-4">My repository list:</p>
              {dataRepos.map((repos, index) => {
                return (
                  <li key={index}>
                    <a href={repos.html_url}>➞ {repos.name}</a>
                  </li>
                );
              })}
            </ul>
          </aside>
        </div>
      </div>
    </div>
  );
};

export default Home;
