import axios from "axios";
import Head from "next/head";
import { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

const Home = () => {
  const [userName, setUserName] = useState("");
  const [avatarUrl, setAvatarUrl] = useState("");
  const [bio, setBio] = useState("");
  const [publicRepos, setPublicRepos] = useState(0);
  const [selected, setSelected] = useState(false);
  const [dataRepos, setDataRepos] = useState([]);

  useEffect(async () => {
    await axios.get(`https://api.github.com/users/cxcarvaj`).then((res) => {
      const data = res.data;
      setUserName(data.name);
      setAvatarUrl(data.avatar_url);
      setBio(data.bio);
      setPublicRepos(data.public_repos);
    });
  }, []);

  useEffect(async () => {
    await axios
      .get(`https://api.github.com/users/cxcarvaj/repos`)
      .then((res) => {
        const data = res.data;
        setDataRepos(data);
      });
  }, []);

  return (
    <div>
      <Navbar />
      <Head>
        <title>Carlos Carvajal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">my profile</a>
        </h1>
      </main>
      <div className="container">
        <div className="mb-6">
          {`My name is ${userName} and I have ${publicRepos} public repositories`}
          <aside className="menu">
            <ul className="menu-list">
              <p className="menu-label mt-4">My repository list:</p>
              {dataRepos.map((repos, index) => {
                return (
                  <li>
                    <a key={index} className={`${selected ? "is-active" : ""}`} href={repos.html_url} onClick={()=>{
                      setSelected(!selected);
                    }}>➞ {repos.name}</a>
                  </li>
                );
              })}
            </ul>
          </aside>
        </div>
      </div>
      <footer>
        <Footer avatarUrl={avatarUrl} />
      </footer>
    </div>
  );
};

export default Home;
